# This is a GitHub App Manifest. These settings will be used by default when
# initially configuring your GitHub App.
#
# NOTE: changing this file will not update your GitHub App settings.
# You must visit github.com/settings/apps/your-app-name to edit them.
#
# Read more about configuring your GitHub App:
# https://probot.github.io/docs/development/#configuring-a-github-app
#
# Read more about GitHub App Manifests:
# https://developer.github.com/apps/building-github-apps/creating-github-apps-from-a-manifest/

# The list of events the GitHub App subscribes to.
default_events:
  - check_run
  - check_suite
  - commit_comment
  - create
  - delete
  - deployment
  - deployment_status
  - fork
  - gollum
  - issue_comment
  - issues
  - label
  - milestone
  - member
  - membership
  - org_block
  - organization
  - page_build
  - project
  - project_card
  - project_column
  - public
  - pull_request
  - pull_request_review
  - pull_request_review_comment
  - push
  - release
  - repository
  - repository_import
  - status
  - team
  - team_add
  - watch

# The set of permissions needed by the GitHub App.
default_permissions:
  # Repository creation, deletion, settings, teams, and collaborators.
  administration: write

  # Checks on code.
  checks: write

  # Repository contents, commits, branches, downloads, releases, and merges.
  contents: write

  # Deployments and deployment statuses.
  deployments: write

  # Issues and related comments, assignees, labels, and milestones.
  issues: write

  # Search repositories, list collaborators, and access repository metadata.
  metadata: read  # Metadata is always read-only

  # Retrieve Pages statuses, configuration, and builds, as well as create new builds.
  pages: write

  # Pull requests and related comments, assignees, labels, milestones, and merges.
  pull_requests: write

  # Manage the post-receive hooks for a repository.
  repository_hooks: write

  # Manage repository projects, columns, and cards.
  repository_projects: write

  # Retrieve security vulnerability alerts.
  vulnerability_alerts: write

  # Commit statuses.
  statuses: write

  # Organization members and teams.
  members: write

  # View and manage users blocked by the organization.
  organization_user_blocking: write

  # Manage organization projects, columns, and cards.
  organization_projects: write

  # Manage team discussions and related comments.
  team_discussions: write

  # Manage the post-receive hooks for an organization.
  organization_hooks: write

  # Get notified of, and update, content references.
  organization_administration: write

# The name of the GitHub App. Defaults to the name specified in package.json
# name: My Probot App

# The homepage of your GitHub App.
# url: https://example.com/

# A description of the GitHub App.
# description: A description of my awesome app

# Set to true when your GitHub App is available to the public or false when it is only accessible to the owner of the app.
# Default: true
# public: false